# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install NativeFileDialogSharp
      run: dotnet add Fushigi/Fushigi.csproj package NativeFileDialogSharp --version 0.6.0-alpha
    - name: Install Newtonsoft.Json
      run: dotnet add Fushigi/Fushigi.csproj package Newtonsoft.Json 
    - name: Install Silk.NET.Core
      run: dotnet add Fushigi/Fushigi.csproj package Silk.NET.Core --version 2.17.1 
    - name: Install Silk.NET.Input
      run: dotnet add Fushigi/Fushigi.csproj package Silk.NET.Input  --version 2.17.1 
    - name: Install Silk.NET.Core
      run: dotnet add Fushigi/Fushigi.csproj package Silk.NET.Core  --version 2.17.1 
    - name: Install Silk.NET.GLFW
      run: dotnet add Fushigi/Fushigi.csproj package Silk.NET.GLFW  --version 2.17.1 
    - name: Install Silk.NET.OpenGL.Extensions.ImGui
      run: dotnet add Fushigi/Fushigi.csproj package Silk.NET.OpenGL.Extensions.ImGui  --version 2.17.1 
    - name: Install StbImageSharp
      run: dotnet add Fushigi/Fushigi.csproj package StbImageSharp 
    - name: Install ZstdNet
      run: dotnet add Fushigi/Fushigi.csproj package ZstdSharp.Port
    - name: Restore dependencies
      run: dotnet restore Fushigi/Fushigi.sln
    - name: Build
      run: dotnet build Fushigi/Fushigi.sln --no-restore 
    - name: Build Mac Silicon
      run: dotnet build Fushigi/Fushigi.sln -r osx-arm64 --no-restore
    - name: Build Mac x64
      run: dotnet build Fushigi/Fushigi.sln -r osx-x64 --no-restore
